version: 2.1


orbs:
  welcome: circleci/welcome-orb@0.4.1
  python: circleci/python@1.2


workflows:
  Welcome:
    jobs:
      - welcome/run

  Testing:
    jobs:
      - Python


jobs:
  Python:
    # working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: Run Python tests
          command: |
            cd tests/python/
            pytest