version: 2.1


orbs:
  welcome: circleci/welcome-orb@0.4.1
  python: circleci/python@1.2


workflows:
  Welcome:
    jobs:
      - welcome/run

  Testing:
    jobs:
      - Python


jobs:
  Python:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.9.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: 
          name: Grant CircleCI access to dependency locations
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
      # - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Python dependencies
          command: |
            pip install pipenv
            pipenv install pytest coverage
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            # - "/usr/local/bin"
            # - "/usr/local/lib/python3.9/site-packages"
      - run:
          name: Run Python tests
          command: |
            cd tests/python/
            pipenv run python3 ./test_dummy.py
#            pipenv run pytest